[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/"]
ffi = true
gas_price = 0
block_base_fee_per_gas = 0
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
